name: delayed_future
description: A Dart extension that allows to delay your Futures.
version: 1.0.3
homepage: https://github.com/nivisi/delayed_future
repository: https://github.com/nivisi/delayed_future
issue_tracker: https://github.com/nivisi/delayed_future/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
